# Generated by Django 2.2.5 on 2021-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('summary', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('genres', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='poster')),
            ],
        ),
    ]
